CREATE TABLE `user`(
	idUser INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(31) NOT NULL,
	surname VARCHAR(31) NOT NULL,
	email VARCHAR(63) NOT NULL UNIQUE,
	password_hash VARCHAR(511) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `session`(
	idSession INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	session_uuid VARCHAR(1023) NOT NULL,
	ttl TIMESTAMP DEFAULT (TIMESTAMPADD(DAY, 7, CURRENT_TIMESTAMP)),	
 	fk_user INT NOT NULL,
	FOREIGN KEY (fk_user) REFERENCES user(idUser) ON DELETE CASCADE
);

CREATE TABLE `AccessLog` (
 	idAccessLog INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
 	user_email varchar(63),
 	action_type VARCHAR(31),
 	target_table VARCHAR(15),
 	target_id INT,
 	ip_address VARCHAR(31),
 	user_agent VARCHAR(1023),
 	started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
 );

