#version: '3.8'



services:

  #**** Ta del kopirata za svojo mikrostoritev (vse do ***** )
  gamification_database:
    build:
      context: ./Gamification/mysql  #tu specificiraj pot do baze mikrostoritve
      dockerfile: ./Dockerfile
    container_name: gamification_mysql_db #ime containerja za svojo bazo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_GAMIFICATION}
      MYSQL_DATABASE: ${DB_NAME_GAMIFICATION}
    ports:
      - "6105:6105"
    volumes:
      - gamification_db_data:/var/lib/gamification_mysql
    networks:
      - app_network
  gamification_backend:
    build:
      context: ./Gamification #tu specificiraj pot do mikrostoritve
      dockerfile: ./Dockerfile
    container_name: gamification_backend #ime backenda za svojo mikrostoritev
    ports:
      - "6005:6005" #tu podajta port ki ga storitev uporablja
    depends_on:
      - gamification_database #tu podatjta ime containerja za bazo storitve (nad tem containerjem), na katero je odvisna mikrostoritev
    environment:
      - DB_HOST=${DB_HOST_GAMIFICATION}
      - DB_USER=${DB_USER_GAMIFICATION}
      - DB_PASSWORD=${DB_PASSWORD_GAMIFICATION}
      - DB_NAME=${DB_NAME_GAMIFICATION}

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network
#*******   

  shipping_database:
    build:
      context: ./Shipping/mysql 
      dockerfile: ./Dockerfile
    container_name: shipping_mysql_db 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_SHIPPING}
      MYSQL_DATABASE: ${DB_NAME_SHIPPING}
    ports:
      - "6104:6104"
    volumes:
      - shipping_db_data:/var/lib/gamification_mysql
    networks:
      - app_network
  shipping_backend:
    build:
      context: ./Shipping 
      dockerfile: ./Dockerfile
    container_name: shipping_backend 
    ports:
      - "6004:6004" 
    depends_on:
      - shipping_database 
    environment:
      - DB_HOST=${DB_HOST_SHIPPING}
      - DB_USER=${DB_USER_SHIPPING}
      - DB_PASSWORD=${DB_PASSWORD_SHIPPING}
      - DB_NAME=${DB_NAME_SHIPPING}

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network

volumes:
  gamification_db_data:
  shipping_db_data:
networks:
  app_network:
    driver: bridge

    
